- name: Install Zsh if not already installed
  ansible.builtin.dnf:
    name: zsh
    state: present

- name: Install Oh My Zsh
  ansible.builtin.shell: |
    set -o pipefail
    yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  args:
    creates: /home/{{ ansible_user }}/.oh-my-zsh
  become: false

- name: Change default shell to Zsh
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /usr/bin/zsh
