services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      TZ: 'America/New_York'
      FTLCONF_webserver_api_password: 'pihole'
    volumes:
      - './etc/pihole:/etc/pihole'
      #- './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
