services:

  memcached:
    image: memcached:1.6.29
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m  # Set the maximum memory usage
      - MEMCACHED_THREADS=4       # Number of threads to use
    networks:
      - lgtm

  tempo:
    container_name: tempo
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./etc/tempo/tempo.yml:/etc/tempo.yml
      - tempo_data:/var/tempo
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"    # tempo
      - "9095:9095"    # tempo grpc
      - "4317:4317"    # otlp grpc
      - "4318:4318"    # otlp http
      - "9411:9411"    # zipkin
    depends_on:
      - memcached
    networks:
      - lgtm

  pyroscope:
    container_name: pyroscope
    image: grafana/pyroscope:latest
    ports:
      - 4040:4040
    networks:
      - lgtm

  loki:
    image: grafana/loki:3.4
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./etc/loki:/etc/loki
    command: -config.file=/etc/loki/loki.yaml
    networks:
      - lgtm

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    volumes:
      - ./etc/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    ports:
      - 12345:12345
    networks:
      - lgtm

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./etc/prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - lgtm

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./etc/grafana:/etc/grafana/provisioning/datasources
    networks:
      - lgtm

volumes:
  prom_data:
  tempo_data:

networks:
  lgtm:
    name: lgtm
    external: true