apiVersion: v1
kind: Secret
metadata:
  name: tunnel-token
stringData:
  token: <>
---
apiVersion: v1
kind: Secret
metadata:
  name: lockin-secrets
  namespace: default
type: Opaque
stringData:
  DB_URI: <>
