apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: default
spec:
  interval: 1m0s
  provider: generic
  url: https://prometheus-community.github.io/helm-charts
