apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: default
spec:
  interval: 1m0s
  provider: generic
  url: https://prometheus-community.github.io/helm-charts
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: default
spec:
  interval: 1m0s
  provider: generic
  url: https://charts.longhorn.io
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cilium
  namespace: default
spec:
  interval: 1m0s
  provider: generic
  url: https://helm.cilium.io/
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubestack
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/jiechenmc/kubestack
  ref:
    branch: main
  ignore: |
    /*
    !/charts
