apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy
spec:
  ingressClassName: traefik
  rules:
    - host: alloy.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: alloy-cluster
                port:
                  number: 12345
