- name: Deploy Cilium CNI with Helm
  delegate_to: 127.0.0.1
  become: false
  block:
    - name: Ensure Cilium Helm repo is present
      kubernetes.core.helm_repository:
        name: cilium
        repo_url: "https://helm.cilium.io/"
        force: true

    - name: Deploy or upgrade Cilium
      kubernetes.core.helm:
        name: cilium
        chart_ref: cilium/cilium
        release_namespace: kube-system
        create_namespace: false
        values:
          k8sServiceHost: "{{ api_endpoint }}"
          k8sServicePort: 6443
          kubeProxyReplacement: true
          ipam:
            operator:
              clusterPoolIPv4PodCIDRList:
                - "10.42.0.0/16"
          hubble:
            enabled: true
            relay:
              enabled: true
            ui:
              enabled: true
