apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubestack
  namespace: default
spec:
  interval: 1m0s
  url: https://github.com/jiechenmc/kubestack
  ref:
    branch: main
  ignore: |
    /*
    !/charts/code-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nx-code
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/code-server
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kubestack
      version: 4.96.4
  interval: 1m0s
