apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: code-server
configMapGenerator:
  - name: code-server-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml