apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
spec:
  ingressClassName: nginx
  rules:
    - host: kamrui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-minio
                port:
                  number: 9001
