---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: monitor
  annotations:
  traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: minio.kamrui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-minio
                port:
                  number: 9001
