apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: minio
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /minio
            pathType: Prefix
            backend:
              service:
                name: my-minio
                port:
                  number: 9001
