apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: minio-strip
  namespace: minio
spec:
  stripPrefix:
    prefixes:
      - "/minio"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: monitor
  annotations:
  traefik.ingress.kubernetes.io/router.entrypoints: web
  # traefik.ingress.kubernetes.io/router.middlewares: default-minio-strip@kubernetescrd

spec:
  ingressClassName: traefik
  rules:
    - host: minio.kamrui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-kube-stack-minio
                port:
                  number: 9001
