apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio
configMapGenerator:
  - name: minio-values
    files:
      - values.yaml=helm/minio/values.yaml
configurations:
  - kustomizeconfig.yaml
