apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nx-monitor
  namespace: default
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
      version: 69.2.0
  targetNamespace: monitor
  interval: 1m0s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared
  namespace: monitor
  labels:
    release: nx-monitor
spec:
  selector:
    matchLabels:
      app: cloudflared-service
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
