crio_version: v1.36
k8s_version: v1.36
k8s_api_ip: 10.144.138.245
k8s_svc_port: 6443
cilium_version: 1.19.4
pod_cidr: 10.244.0.0/16
service_cidr: "10.96.0.0/12"
k8s_api_iface: enp4s0
k8s_api_prefix: 24
k8s_api_gateway: 10.144.138.1
k8s_api_dns: "10.144.138.1"
lb_ip_start: 10.144.138.200
lb_ip_stop: 10.144.138.220
hubble_metrics:
  - dns
  - drop
  - tcp
  - icmp
  - flow:sourceContext=reserved-identity;destinationContext=reserved-identity
  - port-distribution:destinationContext=reserved-identity
  - policy:sourceContext=reserved-identity;destinationContext=reserved-identity
rook_ceph_chart: /root/kubestack/kubernetes/helm/rook-ceph
ceph_image: quay.io/ceph/ceph:v20.2.4
ceph_node: localhost.localdomain
ceph_device: /dev/disk/by-id/ata-T-FORCE_T253TY001T_TPBF2503200040100652
ceph_csi_drivers_chart: /root/kubestack/kubernetes/helm/ceph-csi-drivers
cnpg_chart: /root/kubestack/kubernetes/helm/cloudnative-pg
kps_chart: /root/kubestack/kubernetes/helm/kube-prometheus-stack
cortex_chart: /root/kubestack/kubernetes/helm/cortex
tempo_chart: /root/kubestack/kubernetes/helm/tempo
otelcol_chart: /root/kubestack/kubernetes/helm/opentelemetry-collector
loki_chart: /root/kubestack/kubernetes/helm/loki
snapshot_controller_chart: /root/kubestack/kubernetes/helm/snapshot-controller
metrics_server_chart: /root/kubestack/kubernetes/helm/metrics-server
infisical_operator_chart: /root/kubestack/kubernetes/helm/secrets-operator
arc_controller_chart: /root/kubestack/kubernetes/helm/gha-runner-scale-set-controller
arc_scale_set_chart: /root/kubestack/kubernetes/helm/gha-runner-scale-set
github_runners_manifest: /root/kubestack/kubernetes/manifests/github-runners.yaml
