apiVersion: v1
kind: Namespace
metadata:
  name: knative-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: knative-operator
  namespace: knative-operator
spec:
  interval: 1m0s
  provider: generic
  url: https://knative.github.io/operator
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative
  namespace: knative-operator
spec:
  chart:
    spec:
      chart: knative-operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: knative-operator
      version: 1.17.1
  interval: 1m0s
