apiVersion: v1
kind: Namespace
metadata:
  name: apache-airflow
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: apache-airflow
  namespace: apache-airflow
spec:
  interval: 1m0s
  provider: generic
  url: https://airflow.apache.org
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: knative
  namespace: apache-airflow
spec:
  chart:
    spec:
      chart: airflow
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: apache-airflow
      version: 1.15.0
  createUserJob:
    useHelmHooks: false
    applyCustomEnv: false
  migrateDatabaseJob:
    useHelmHooks: false
    applyCustomEnv: false
  interval: 1m0s
