- name: Deploy Traefik Ingress Controller with Helm
  delegate_to: localhost
  become: false
  block:
    - name: Ensure Traefik Helm repo is present
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"
        force: true

    - name: Deploy or upgrade Traefik
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: traefik
        create_namespace: true
        values:
          deployment:
            replicas: 1
            hostNetwork: true

          ports:
            web:
              port: 80
            websecure:
              port: 443

          service:
            type: LoadBalancer

          ingressRoute:
            dashboard:
              enabled: true

          additionalArguments:
            - "--api.dashboard=true"

- name: Deploy MetalLB with Helm
  delegate_to: localhost
  become: false
  block:
    - name: Ensure MetalLB Helm repo is present
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        force: true

    - name: Install MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        values:
          speaker:
            tolerateMaster: true

    - name: Configure MetalLB address pool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: lan-pool
            namespace: metallb-system
          spec:
            addresses:
              - 10.144.138.227-10.144.138.246

    - name: Enable L2 advertisement
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2
            namespace: metallb-system
