- name: Deploy Traefik Ingress Controller with Helm
  delegate_to: localhost
  become: false
  block:
    - name: Ensure Traefik Helm repo is present
      kubernetes.core.helm_repository:
        name: traefik
        repo_url: "https://traefik.github.io/charts"
        force: true

    - name: Deploy or upgrade Traefik
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: kube-system
        values_files: "{{ playbook_dir }}/values.yaml"

- name: Deploy MetalLB with Helm
  delegate_to: localhost
  become: false
  block:
    - name: Ensure MetalLB Helm repo is present
      kubernetes.core.helm_repository:
        name: metallb
        repo_url: https://metallb.github.io/metallb
        force: true

    - name: Install MetalLB
      kubernetes.core.helm:
        name: metallb
        chart_ref: metallb/metallb
        release_namespace: metallb-system
        create_namespace: true
        wait: true
        values:
          speaker:
            tolerateMaster: true

    - name: Configure MetalLB address pool
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: lan-pool
            namespace: metallb-system
          spec:
            addresses:
              - 10.144.138.227-10.144.138.246

    - name: Enable L2 advertisement
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: l2
            namespace: metallb-system

- name: Ensure Prometheus community repo is present
  delegate_to: localhost
  become: false
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Ensure Grafana repo is present
  delegate_to: localhost
  become: false
  kubernetes.core.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Deploy Prometheus
  delegate_to: localhost
  become: false
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: monitoring
    create_namespace: true

- name: Deploy Grafana
  delegate_to: localhost
  become: false
  kubernetes.core.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring
    values:
      replicas: 1
      adminUser: admin
      adminPassword: admin
