apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true

- name: Loki
  type: loki
  access: proxy 
  url: http://loki:3100
  basicAuth: false
  isDefault: false 

- name: Tempo
  type: tempo
  access: proxy 
  url: http://tempo:3200
  basicAuth: false
  isDefault: false 

- name: Pyroscope
  type: grafana-pyroscope-datasource
  access: proxy 
  url: http://pyroscope:4040
  basicAuth: false
  isDefault: false 