---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami
  namespace: minio
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 15.0.2
  timeout: 1m0s
  url: oci://registry-1.docker.io/bitnamicharts/minio
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-minio
  namespace: minio
spec:
  chart:
    spec:
      chart: minio
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: OCIRepository
        name: bitnami
      version: 15.0.2
  interval: 1m0s
