---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: init
  namespace: flux-system
spec:
  chart:
    spec:
      chart: prometheus-community
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
      version: "*"
  interval: 1m0s
