---
- name: Configure Rocky Linux Workstation
  hosts: server
  become: true
  become_method: ansible.builtin.sudo
  remote_user: rocky
  roles:
    - devtools
    - ohmyzsh
    - homebrew
    - helm
    - k3s
