apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nx-monitor
  namespace: default
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: default
      version: 69.2.0
  targetNamespace: monitor
  interval: 1m0s
---

