apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nx-longhorn
  namespace: default
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: default
      version: 1.8.1
  targetNamespace: longhorn-system
  interval: 1m0s
