---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmChart
metadata:
  labels:
    helm.toolkit.fluxcd.io/name: my-kube-stack
    helm.toolkit.fluxcd.io/namespace: monitor
  name: monitor-my-kube-stack
  namespace: monitor
spec:
  chart: kube-prometheus-stack
  interval: 1m0s
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: prometheus-community
  version: "*"
