---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prometheus-operator
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/nx/monitor/prometheus"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitors
  namespace: flux-system
spec:
  dependsOn:
    - name: prometheus-operator
  interval: 5m
  path: "./clusters/nx/monitor/monitors"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
